{"name": "Logowanie na konto administracyjne bez wypelnienia pol formularza", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"main-wrapper\"]\n\n", "trace": "  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\(2)_login_negative_steps.py\", line 20, in step_valid_login\n    assert context.driver.find_element_by_id(\"main-wrapper\")\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in find_element_by_id\n    return self.find_element(by=By.ID, value=id_)\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Uzytkownik wchodzi na strone logowania negativ", "status": "passed", "start": 1559230140846, "stop": 1559230156973}, {"name": "When Uzytkownik nie wypelnia pol formularza", "status": "passed", "start": 1559230156973, "stop": 1559230157297}, {"name": "Then Uzytkownik probuje zalogowac sie do panelu", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"main-wrapper\"]\n\n", "trace": "  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\(2)_login_negative_steps.py\", line 20, in step_valid_login\n    assert context.driver.find_element_by_id(\"main-wrapper\")\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in find_element_by_id\n    return self.find_element(by=By.ID, value=id_)\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\marci\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1559230157297, "stop": 1559230159583}], "start": 1559230140842, "stop": 1559230159583, "uuid": "8eace119-3d40-4ad8-940c-d31ca1706a44", "historyId": "48aa9cefc63a3a42089b320b672878cc", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}